apiVersion: v1
kind: Secret
metadata:
  name: repo-demo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/LarsWinters/crossplane-demo.git
